name: Get new lineages from pango

on:
   schedule:
     - cron: '*/5 * * * *'

jobs:
    scheduled_check:
       runs-on: ubuntu-20.04
       steps:
         - name: process data
           run: |
             echo "starting update"
             python curated_reports_prep/generate_curated_lineages_json.py
             echo "removing log file"
             rm curated_reports_prep/curated_lineages_json.log
         - name: commit if output is different 
           run: |
               echo "running git diff, committing if different"
               if [[($(git status web/src/assets/genomics/curated_lineages.json --porcelain | wc -c) -ne 0)]]; then
                  echo "changes were made, adding new lineage info"
               else
                  echo "no changes were made, doing nothing."
               fi; 
